Update CollectSamErrorMetrics.wdl
broadinstitute/TAG-public pull request #41
Opened 2023-08-18 18:41 UTC by lfleming1022

Adding more error metrics to collect

2023-08-30 11:30 UTC, yueyaog approved these changes

2023-09-08 14:42 UTC, fleharty requested changes

2023-09-08 14:42 UTC, fleharty commented on CollectSamError/CollectSamErrorMetrics.wdl
> +        ERROR_METRICS="ERROR" \
Can you remove the MAPPING_QUALITY stratifier from all stratifiers.  Add the -Minimum mapping quality 60 option.

2023-09-08 15:02 UTC, fleharty requested changes
A few more lines to remove.

2023-09-08 15:02 UTC, fleharty commented on CollectSamError/CollectSamErrorMetrics.wdl
> +        ERROR_METRICS="ERROR:CYCLE:BASE_QUALITY:ONE_BASE_PADDED_CONTEXT" \
Let's remove this context:
ERROR_METRICS="ERROR:CYCLE:BASE_QUALITY:ONE_BASE_PADDED_CONTEX

2023-09-08 15:02 UTC, fleharty commented on CollectSamError/CollectSamErrorMetrics.wdl
> +        ERROR_METRICS="OVERLAPPING_ERROR:CYCLE:BASE_QUALITY:ONE_BASE_PADDED_CONTEXT" \
Let's remove this context:
ERROR_METRICS="OVERLAPPING_ERROR:CYCLE:BASE_QUALITY:ONE_BASE_PADDED_CONTEXT" \

2023-09-08 15:02 UTC, fleharty commented on CollectSamError/CollectSamErrorMetrics.wdl
> +        ERROR_METRICS="ERROR:CYCLE" \
CYCLE is specified twice.

2023-09-08 15:02 UTC, fleharty commented on CollectSamError/CollectSamErrorMetrics.wdl
> +        ERROR_METRICS="ERROR" \
Also remove:
ERROR_METRICS="ERROR" \

2023-09-08 15:17 UTC, fleharty requested changes

2023-09-08 15:17 UTC, fleharty commented on CollectSamError/CollectSamErrorMetrics.wdl
>          ERROR_METRICS="ERROR:INSERT_LENGTH" \
Can you add:
OVERLAPPING_ERROR:INSERT_LENGTH
OVERLAPPING_ERROR:GC_CONTENT

and add an option that we can expose to Terra to the probability with a default of 1.

2023-09-08 15:23 UTC, fleharty approved these changes
Thanks @laurafleming-1022 Looks great!

2023-09-08 15:24 UTC, merged